require("urca")

set.seed(1)

# Create a random walk
z <- rep(0, 10000)
for (i in 2:10000) z[i] <- z[i-1] + rnorm(1)

# Create three time series derived from this random walk, with some noise
p <- q <- r <- rep(0, 10000)
p <- 0.3*z + rnorm(10000)
q <- 0.6*z + rnorm(10000)
r <- 0.2*z + rnorm(10000)

# Performing the Johansen test and p,q,r
jotest=ca.jo(data.frame(p,q,r), type="trace", K=2, ecdet="none", spec="longrun") 
# K is the number of lags >= 2
# ecdet refers to whether to use a constant or drift term in the model
# spec="longrun" refers to the specification of the VECM (Vector Error Correction Model)
# This parameter can be spec="longrun" or spec="transitory".
summary(jotest)

# the largest eigenvalue is approximately 0.3375. It corresponds to the vector given
# under the column p.l2, and is approximately equal to (1:000; -2.255; 5.265)

s = 1.000*p - 2.255 *q + 5.265*r
plot(s, type="l")

library("tseries")
adf.test(s)
# p-val is very low!!


# Financial data:
library("quantmod")

getSymbols("EWA", from="2006-04-26", to="2012-04-09")
getSymbols("EWC", from="2006-04-26", to="2012-04-09")
getSymbols("IGE", from="2006-04-26", to="2012-04-09")

ewaAdj = unclass(EWA$EWA.Adjusted)
ewcAdj = unclass(EWC$EWC.Adjusted)
igeAdj = unclass(IGE$IGE.Adjusted)

jotest=ca.jo(data.frame(ewaAdj,ewcAdj,igeAdj), type="trace",
K=2, ecdet="none", spec="longrun")
summary(jotest)

s = ewaAdj - 1.008*ewcAdj + 0.227*igeAdj
adf.test(s)
#p-value is 0.0835 - not below 0.05 so maybe we can't reject the null hypothesis that this is non-stationary

# Different instruments that all track to S&P:
getSymbols("SPY", from="2015-01-01", to="2015-12-31")
getSymbols("IVV", from="2015-01-01", to="2015-12-31")
getSymbols("VOO", from="2015-01-01", to="2015-12-31")

spyAdj = unclass(SPY$SPY.Adjusted)
ivvAdj = unclass(IVV$IVV.Adjusted)
vooAdj = unclass(VOO$VOO.Adjusted)

jotest=ca.jo(data.frame(spyAdj,ivvAdj,vooAdj), type="trace", K=2,
ecdet="none", spec="longrun")
summary(jotest)
# r \leq 2 we reject null only at the 5% level (compared to far exceeding the 1% level for 0 and 1 ) so have to be careful that r may be 2.

s = spyAdj - 0.347*ivvAdj - 0.710*vooAdj
adf.test(s)

