set.seed(1)
# AR:

# AR(1):

# With alpha_1 = 0.6
x <- w <- rnorm(100)
for (t in 2:100) x[t] <- 0.6*x[t-1] + w[t]

# Plotting the time series and its autocorrelation plot
layout(1:2)
plot(x, type="l")
acf(x)

# Use ar command to fit an autoregressive model to our simulated process (using MLE)
x.ar <- ar(x, method = "mle")
x.ar$order 
# The output is 1 - yay! (Because this matches the parameter 1 we set in our model)

x.ar$ar # Find alpha_1
# Pretty close!

# Finding a 95% confidence interval for the parameter
x.ar$ar + c(-1.96, 1.96)*c(sqrt(x.ar$asy.var))

# Now the same with alpha_1 = -0.6
x <- w <- rnorm(100)
for (t in 2:100) x[t] <- -0.6*x[t-1] + w[t]
layout(1:2)
plot(x, type="l")
acf(x)

x <- w <- rnorm(100)
for (t in 2:100) x[t] <- -0.6*x[t-1] + w[t]

x.ar <- ar(x, method = "mle")
x.ar$order
x.ar$ar



# AR(2): We shall repeat this for an AR(2) model
# alpha_1 = 2/3 and alpha_2 = -1/3
x <- w <- rnorm(100)
for (t in 3:100) x[t] <- 0.666*x[t-1] - 0.333*x[t-2] + w[t]
layout(1:2)
plot(x, type="l")
acf(x)

x.ar <- ar(x, method = "mle")
x.ar$order
x.ar$ar

# Now we look at financial data
# In particular, Amazon stock price data
layout(1:1)
require(quantmod)
getSymbols("AMZN")
tail(AMZN)

# Plotting the closing price
plot(Cl(AMZN))

# Plotting the differenced log returns
amznrt = diff(log(Cl(AMZN))) 
plot(amznrt)

# Plotting the autocorrelation of these differenced log returns
acf(amznrt, na.action=na.omit)

# Fitting an AR model to them
amznrt.ar <- ar(amznrt, na.action=na.omit)
amznrt.ar$order
# Order 20! - that isn't a factorial, don't worry :) 

# Seeing the coefficients
amznrt.ar$ar