#ARMA(1,1) model with alpha_1 = 0.5, beta_1 = -0.5, and plotting the autocorrelation
set.seed(1)
x <- arima.sim(n=1000, model=list(ar=0.5, ma=-0.5))
plot(x)

acf(x)

# Fitting an ARMA(1,1), and finding CI's for each coefficient
arima(x, order=c(1, 0, 1))

0.6785 + c(-1.96, 1.96)*0.167
-0.7311 + c(-1.96, 1.96)*0.155

#ARMA(2,2) with alpha_1 = 0.5, alpha_2 = -0.25, beta_1 = 0.5, beta_2 = -0.3
x <- arima.sim(n=1000, model=list(ar=c(0.5, -0.25), ma=c(0.5, -0.3)))

plot(x)

acf(x)

arima(x, order=c(2, 0, 2))

# CI for AR part
0.3569 + c(-1.96, 1.96)*0.1411
-0.228 + c(-1.96, 1.96)*0.0356

# CI for MA part
0.6464 + c(-1.96, 1.96)*0.1436
-0.1493 + c(-1.96, 1.96)*0.1275

# Choosing the best ARMA(p,q) model
# Simulate 1000 timestamps via an arima model
x <- arima.sim(n=1000, model=list(ar=c(0.5, -0.25, 0.4), ma=c(0.5, -0.3)))

# We want to minimise the aic, so we look at which model does so
# First we initialise the aic at infinity and iterate through potential models
# Updating the final.aic when we see one lower
final.aic <- Inf
final.order <- c(0,0,0)
for (i in 0:4) for (j in 0:4) {
  current.aic <- AIC(arima(x, order=c(i, 0, j)))
  if (current.aic < final.aic) {
    final.aic <- current.aic
    final.order <- c(i, 0, j)
    final.arma <- arima(x, order=final.order)
  }
}

# Return the final aic
final.aic

# Return the final order
final.order
# (4,3) - which is interesting, as it is not (3,2)

# Showing the coefficients 
final.arma

# Plotting the autocorrelation of the residuals of the model vs our original
acf(resid(final.arma))

# Perform Ljung-Box test for 20 Lags to confirm this is good
Box.test(resid(final.arma), lag=20, type="Ljung-Box")
#0.7133 >> 0.05 so really good model


# Financial data, we do the same for the differenced log returns for the s&p500:
require(quantmod)

getSymbols("^GSPC")
sp = diff(log(Cl(GSPC)))

spfinal.aic <- Inf
spfinal.order <- c(0,0,0)
for (i in 0:4) for (j in 0:4) {
  spcurrent.aic <- AIC(arima(sp, order=c(i, 0, j)))
  if (spcurrent.aic < spfinal.aic) {
    spfinal.aic <- spcurrent.aic
    spfinal.order <- c(i, 0, j)
    spfinal.arma <- arima(sp, order=spfinal.order)
  }
}

spfinal.order

acf(resid(spfinal.arma), na.action=na.omit)
# Quite a few high peaks, especially at higher lags.

Box.test(resid(spfinal.arma), lag=20, type="Ljung-Box")
# p-val is very small so this model isnt very good, oh well :(
# Hence there is additional autocorrelation in the residuals that is not explained by the fitted ARMA(2,3) model.


