# GARCH(1,1) - need alpha_1 + beta_1 < 1, otherwise it will be unstable
# Take alpha_0 = 0.2, alpha_1 =0.5 ,beta_1 = 0.3

# Creating the GARCH model
set.seed(2)
a0 <- 0.2
a1 <- 0.5
b1 <- 0.3
w <- rnorm(10000)
eps <- rep(0, 10000)
sigsq <- rep(0, 10000)
for (i in 2:10000) {
  sigsq[i] <- a0 + a1 * (eps[i-1]^2) + b1 * sigsq[i-1]
  eps[i] <- w[i]*sqrt(sigsq[i])
}

# Plot the autocorrelation for the sequence and the sequence squared
acf(eps)

acf(eps^2)
# we see substantial evidence of a conditionally heteroskedastic process via the decay of successive lags.

require(tseries)

# Finding a garch model to fit the data, and show the CI's
eps.garch <- garch(eps, trace=FALSE)
confint(eps.garch)

# Financial data:
require(quantmod)
getSymbols("^FTSE")
ftrt = diff(log(Cl(FTSE)))

plot(ftrt)

# We also need to remove the NA value generated by the differencing procedure
ft <- as.numeric(ftrt)
ft <- ft[!is.na(ft)]

# Fit an arima model
ftfinal.aic <- Inf
ftfinal.order <- c(0,0,0)
for (p in 1:4) for (d in 0:1) for (q in 1:4) {
  ftcurrent.aic <- AIC(arima(ft, order=c(p, d, q)))
  if (ftcurrent.aic < ftfinal.aic) {
    ftfinal.aic <- ftcurrent.aic
    ftfinal.order <- c(p, d, q)
    ftfinal.arima <- arima(ft, order=ftfinal.order)
  }
}

ftfinal.order

# Autocorrelation plot of the residuals
acf(resid(ftfinal.arima))

acf(resid(ftfinal.arima)^2)
# Shows serial correlation

# Fitting a garch model
ft.garch <- garch(ft, trace=F) # trace = F says to not output each bit
ft.res <- ft.garch$res[-1]

# Autocorrelation plot of the residuals with the GARCH model
acf(ft.res)

acf(ft.res^2)
# Pretty good :)

Box.test(resid(ft.garch), lag=20, type="Ljung-Box")
# p-val is 0.9913!!!!!! Very good!

