# MA(1)

# Creating and plotting a MA(1) model with beta_1 = 0.6 and plotting the autocorrelation
set.seed(1)
x <- w <- rnorm(100)
for (t in 2:100) x[t] <- w[t] + 0.6*w[t-1]
layout(1:2)
plot(x, type="l")
acf(x)

# Fitting an MA(1) model - hence order=c(0,0,1) (for AR I and MA parts)
x.ma <- arima(x, order=c(0, 0, 1))
x.ma

# 95% CI for the beta_1 coef.
0.6023 + c(-1.96, 1.96)*0.0827

# Now the same but for beta_1 = -0.6
x <- w <- rnorm(100)
for (t in 2:100) x[t] <- w[t] - 0.6*w[t-1]
layout(1:2)
plot(x, type="l")
acf(x)

x.ma <- arima(x, order=c(0, 0, 1))
x.ma

-0.730 + c(-1.96, 1.96)*0.1008


# Now let's do a MA(3) model

set.seed(3)
x <- w <- rnorm(1000)
for (t in 4:1000) x[t] <- w[t] + 0.6*w[t-1] + 0.4*w[t-2] + 0.3*w[t-3]
layout(1:2)
plot(x, type="l")
acf(x)

x.ma <- arima(x, order=c(0, 0, 3))
x.ma

# CI for the three coefficients
0.544 + c(-1.96, 1.96)*0.0309
0.345 + c(-1.96, 1.96)*0.0349
0.298 + c(-1.96, 1.96)*0.0311


# Now let's use Financial Data
require(quantmod)
getSymbols("AMZN")
amznrt = diff(log(Cl(AMZN)))

# Fitting an MA(1) model on the differenced log returns
amznrt.ma <- arima(amznrt, order=c(0, 0, 1))
amznrt.ma

layout(1:1)

# Plotting the autocorrelation of the residuals of the MA model fitting to the differenced amazon stock returns
acf(amznrt.ma$res[-1])

# Notice that we have a few significant peaks at lags k = 2, k = 11, k = 16 and k = 18,
# indicating that the MA(1) model is unlikely to be a good fit for the behaviour of the AMZN log
# returns, since this does not look like a realisation of white noise.

# Now try MA(2):
amznrt.ma <- arima(amznrt, order=c(0, 0, 2))
amznrt.ma

acf(amznrt.ma$res[-1])
# A few significant peaks

# Now MA(3)
amznrt.ma <- arima(amznrt, order=c(0, 0, 3))

amznrt.ma

acf(amznrt.ma$res[-1])

