# AR:

# AR(1):

# With alpha_1 = 0.6
x <- w <- rnorm(100)
for (t in 2:100) x[t] <- 0.6*x[t-1] + w[t]

layout(1:2)
plot(x, type="l")
acf(x)

# Use ar command to fit an autoregressive model to our simulated process (using MLE)
x.ar <- ar(x, method = "mle")
x.ar$order 
# The output is 1 - yay!

x.ar$ar # Find alpha_1
# Pretty close!

x.ar$ar + c(-1.96, 1.96)*c(sqrt(x.ar$asy.var)) # 95% confidence interval

# Now alpha_1 = -0.6
x <- w <- rnorm(100)
for (t in 2:100) x[t] <- -0.6*x[t-1] + w[t]
layout(1:2)
plot(x, type="l")
acf(x)

x <- w <- rnorm(100)
for (t in 2:100) x[t] <- -0.6*x[t-1] + w[t]

x.ar <- ar(x, method = "mle")
x.ar$order
x.ar$ar



# AR(2):
# alpha_1 = 2/3 and alpha_2 = -1/3
x <- w <- rnorm(100)
for (t in 3:100) x[t] <- 0.666*x[t-1] - 0.333*x[t-2] + w[t]
layout(1:2)
plot(x, type="l")
acf(x)

x.ar <- ar(x, method = "mle")
x.ar$order
x.ar$ar

layout(1:1)
require(quantmod)
getSymbols("AMZN")
tail(AMZN)

plot(Cl(AMZN))

amznrt = diff(log(Cl(AMZN))) # Differenced log returns
plot(amznrt)

acf(amznrt, na.action=na.omit)

amznrt.ar <- ar(amznrt, na.action=na.omit)
amznrt.ar$order

amznrt.ar$ar

amznrt.ar$asy.var

getSymbols("^GSPC")
tail(GSPC)

plot(Cl(GSPC))

gspcrt = diff(log(Cl(GSPC)))
plot(gspcrt)

acf(gspcrt, na.action=na.omit)

gspcrt.ar <- ar(gspcrt, na.action=na.omit)
gspcrt.ar$order

gspcrt.ar$ar

