# The strategy is carried out on a "rolling" basis:
# 1. For each day, n, the previous k days of the differenced logarithmic returns of a stock market
# index are used as a window for fitting an optimal ARIMA and GARCH model.
# 2. The combined model is used to make a prediction for the next day returns.
# 3. If the prediction is negative the stock is shorted at the previous close, while if it is      # positive it is longed.
# 4. If the prediction is the same direction as the previous day then nothing is changed.

install.packages("quantmod")
install.packages("lattice")
install.packages("timeSeries")
install.packages("rugarch")

library(quantmod)
library(lattice)
library(timeSeries)
library(rugarch)

getSymbols("^GSPC", from="2005-01-01")
spReturns = diff(log(Cl(GSPC)))
spReturns[as.character(head(index(Cl(GSPC)),1))] = 0

windowLength = 500
foreLength = length(spReturns) - windowLength
forecasts <- vector(mode="character", length=foreLength)

for (d in 0:foreLength) {
  # Obtain the S&P500 rolling window for this day
  spReturnsOffset = spReturns[(1+d):(windowLength+d)]

  # Fit the ARIMA model
  final.aic <- Inf
  final.order <- c(0,0,0)
  for (p in 0:5) for (q in 0:5) {
    if ( p == 0 && q == 0) {
      next
    }
    arimaFit = tryCatch( arima(spReturnsOffset, order=c(p, 0, q)),
      error=function( err ) FALSE,
      warning=function( err ) FALSE )
    if( !is.logical( arimaFit ) ) {
      current.aic <- AIC(arimaFit)
      if (current.aic < final.aic) {
        final.aic <- current.aic
        final.order <- c(p, 0, q)
        final.arima <- arima(spReturnsOffset, order=final.order)
      }
    } else {
      next
    }
  }

  # Specify and fit the GARCH model
  spec = ugarchspec(
    variance.model=list(garchOrder=c(1,1)),
    mean.model=list(armaOrder=c(
      final.order[1], final.order[3]
    ), include.mean=T),
    distribution.model="sged"
  )
  fit = tryCatch(
    ugarchfit(
      spec, spReturnsOffset, solver = 'hybrid'
    ), error=function(e) e, warning=function(w) w
  )

  # If the GARCH model does not converge, set the direction to "long" else
  # choose the correct forecast direction based on the returns prediction
  # Output the results to the screen and the forecasts vector
  if(is(fit, "warning")) {
    forecasts[d+1] = paste(
      index(spReturnsOffset[windowLength]), 1, sep=","
    )
   print(
     paste(
       index(spReturnsOffset[windowLength]), 1, sep=","
     )
   )
  } else {
    fore = ugarchforecast(fit, n.ahead=1)
    ind = fore@forecast$seriesFor
    forecasts[d+1] = paste(
     colnames(ind), ifelse(ind[1] < 0, -1, 1), sep=","
    )
    print(paste(colnames(ind), ifelse(ind[1] < 0, -1, 1), sep=","))
  }
}

write.csv(forecasts, file="forecasts.csv", row.names=FALSE)



setwd("/Users/patrickfahy99/Documents/Time Series Analysis R/")

spArimaGarch = as.xts(
  read.zoo(
    file="forecasts_new.csv", format="%Y-%m-%d", header=F, sep=","
  )
)

spIntersect = merge( spArimaGarch[,1], spReturns, all=F )

spArimaGarchReturns = spIntersect[,1] * spIntersect[,2]

spArimaGarchCurve = log( cumprod( 1 + spArimaGarchReturns ) )
spBuyHoldCurve = log( cumprod( 1 + spIntersect[,2] ) )
spCombinedCurve = merge( spArimaGarchCurve, spBuyHoldCurve, all=F )

require(lattice)

xyplot(
  spCombinedCurve,
  superpose=T,
  col=c("darkred", "darkblue"),
  lwd=2,
  key=list(
    text=list(
      c("ARIMA+GARCH", "Buy & Hold")
    ),
    lines=list(
      lwd=2, col=c("darkred", "darkblue")
    )
  )
)

